In [ ]:
#Create a null vector of size 10 but the fifth value which is 1.

In [6]:
import numpy as np
nullVector = np.zeros(10,dtype = 'int32')
nullVector[4]=1

In [7]:
nullVector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [13]:
#Create a vector with values ranging from 10 to 49

Vector = np.random.randint(10,49)

In [14]:
Vector

20

In [24]:
#Create a 3x3 matrix with values ranging from 0 to 8
Matrix3x3 = np.random.randint(0,9,size = (3,3))

In [25]:
Matrix3x3

array([[8, 7, 5],
       [6, 0, 7],
       [0, 8, 4]])

In [30]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values.

In [31]:
array = np.random.randint(0,100,size =(10,10))

In [32]:
array

array([[ 5, 53, 30, 75,  4, 38, 19,  5, 43, 52],
       [34, 39, 97, 86, 98, 65, 13, 21, 41, 36],
       [71, 72, 85, 52, 41, 87, 70,  3, 69, 99],
       [23, 14, 68, 51,  9, 11, 41, 19, 25,  9],
       [38, 89, 37, 34,  9, 98, 72,  0, 26, 83],
       [33, 24, 31, 27, 59, 96, 69, 53, 21, 98],
       [ 6, 78, 22, 55, 63, 12, 98, 45,  8, 19],
       [62, 90, 56,  9,  6, 36, 66, 53, 35, 44],
       [44, 66, 35, 76, 15, 79, 24,  1, 36, 11],
       [90, 66, 26, 34, 83, 10, 60,  6, 52,  5]])

In [35]:
array.min()

0

In [37]:
array.max()

99

In [38]:
#Create a random vector of size 30 and find the mean value.
randomvector = np.random.rand(30)

In [39]:
randomvector

array([0.49748272, 0.38284596, 0.68397872, 0.65658706, 0.82095971,
       0.31788625, 0.7047129 , 0.82431364, 0.42417598, 0.13104101,
       0.34855797, 0.65772506, 0.92141586, 0.54975435, 0.5449306 ,
       0.1402983 , 0.8225377 , 0.55120707, 0.74898083, 0.30809001,
       0.92433274, 0.51107604, 0.27220473, 0.15795178, 0.2197519 ,
       0.84096659, 0.14089805, 0.12508833, 0.9275724 , 0.02196727])

In [40]:
randomvector.mean()

0.5059763839676455